name: dilettatest
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  brasil_fields: ^1.14.3
  cached_network_image: ^3.4.1
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  get_it: ^7.6.7
  intl: ^0.19.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  http_mock_adapter: ^0.6.1


flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700